export enum NotificationType {
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  KYC_APPROVED = 'KYC_APPROVED',
  NEW_FEATURE = 'NEW_FEATURE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  ACCOUNT_UPDATE = 'ACCOUNT_UPDATE'
} 